### ISSUE TITLE
Wrong time

### ISSUE THREAD

**Issue by k4wo** [howljs/react-native-calendar-kit#22]
I'm testing the library and it displays wrong time.
```
"@howljs/calendar-kit": "^1.10.2"
```

```ts
import {StyleSheet} from 'react-native';
import React from 'react';
import {TimelineCalendar, EventItem} from '@howljs/calendar-kit';

const exampleEvents: EventItem[] = [
  {
    id: '1',
    title: 'Test1',
    start: '2022-12-20T11:00:44.098Z',
    end: '2022-12-20T12:00:44.301Z',
    color: '#A3C7D6',
  },
  {
    id: '2',
    title: 'test 2',
    start: '2022-12-18T10:00:05.313Z',
    end: '2022-12-18T11:00:05.313Z',
    color: '#B1AFFF',
  },
];

export const Agenda = () => {
  return <TimelineCalendar viewMode="threeDays" events={exampleEvents} />;
};

export default Agenda;
```

And result is like on the screen:
<img width="483" alt="Screenshot 2022-12-20 at 22 15 34" src="https://user-images.githubusercontent.com/7694418/208776999-494364a4-1d1d-438c-a13b-8ec27680559b.png">

There is one hour difference in app in comparison to data (`exampleEvents`). Eg. start: 10 in data but in app 11. Any idea what I'm doing wrong?

PS. Passing `timeZone` prop results in crashing the app (timeZoneData is undefined)

**Comment by howljs** [comment]
I cannot reproduce your problem. :(((
Default events will be displayed in your time zone.
Example:
`
{
    id: '1',
    title: 'Test1',
    start: '2022-12-20T11:00:44.098Z',
    end: '2022-12-20T12:00:44.301Z',
    color: '#A3C7D6',
  }
`

In my timezone: UTC+07:00
It's will start at 18:00
![Simulator Screen Shot - iPhone 14 Pro Max - 2022-12-21 at 16 46 45](https://user-images.githubusercontent.com/33460888/208874790-84c96efb-917f-4480-86b8-fcfb06c4c1df.png)

Or custom timezone:  timeZone="Asia/Tokyo" - UTC+09:00
It's will start at 20:00

![Screenshot 2022-12-21 at 16 48 49](https://user-images.githubusercontent.com/33460888/208875158-3cbefb88-28d7-482b-a6aa-6dd1f928ce1f.png)

**Comment by callaars** [comment]
I do agree that we're also seeing this with our users, we do set timezones but it's often an hour off, for one reason or the other. Still trying to figure out what it does that.

**Comment by callaars** [comment]
Ok so this is a funny one. It's hard to replicate but this is what I did:

Set a custom `timeZone` on the `TimelineCalendar`, doesn't matter which. Then change the local iOS timezone to another zone and you see that the time shifts even if the custom timezone is used.

I haven't dug into the code yet but it feels like there's another function determining the timezone as well. Any ideas @howljs ?

![Screenshot 2023-01-11 at 18 08 56](https://user-images.githubusercontent.com/493348/211884825-70e5e4db-6a45-4c40-a006-7e31783abed1.png)

**Comment by howljs** [comment]
I will check this issue soon. 🥹

**Comment by callaars** [comment]
Thanks man, you're a star. I'm not sure _what_ is going on though.

**Comment by howljs** [comment]
@callaars  I fixed in version [1.11.0](https://github.com/howljs/react-native-calendar-kit/releases/tag/v1.11.0). Thanks for your feedback

**Comment by callaars** [comment]
@howljs unfortunately this didn't fix it. I have found the issue though, it's a `dayjs` bug that happens when you execute `getTimeZoneOffset` in the `utils.ts`.

It's related to this: https://github.com/iamkun/dayjs/issues/1805

**Comment by howljs** [comment]
I don't use the timezone of dayjs because if the react-native version is lower than 0.70.x and hermes is enabled, I can't get the timezone

**Comment by howljs** [comment]
> This particular piece is returning the wrong offset for example when your local device timezone is `Australia/Sydney`: https://github.com/howljs/react-native-calendar-kit/blob/main/src/utils.ts#L416
> 
> 
> 
> I personally wouldn't have used `dayjs` since it has multiple issues like this.

Thanks for your feedback. I will recheck this function: **dayjs().utcOffset()**

**Comment by callaars** [comment]
What you can do is check if DST is being observed and subtract the amount with that. For example the problem appears when a timezone is currently in DST, such as Australia.

**Comment by callaars** [comment]
I've made a PR that will fix this, or at least fix the DST issues.

**Comment by howljs** [comment]
I saw. I'll check it now
