### ISSUE TITLE
[BUG] - When edit event with drag, calendar infinity scroll when i drag from week to week.

### ISSUE THREAD

**Issue by MinhOmega** [howljs/react-native-calendar-kit#41]
Hi author,
I found an issue related to drag events when long press and drag events to edit. I drag the event from week 1 to week 2 same as the video bellow. Can you check it please?
https://vimeo.com/799791066
Thanks

**Comment by howljs** [comment]
I fixed this issue in [v1.12.0](https://github.com/howljs/react-native-calendar-kit/releases/tag/v1.12.0)

**Comment by jyo142** [comment]
Hello @howljs I am still experiencing this issue on Android for version 1.13.2. Any suggestions on how to fix this?
Thank you


https://github.com/howljs/react-native-calendar-kit/assets/4103523/6ab6b56f-4ed0-4873-ae2f-e366d2a97553
